"""Enhance file model

Revision ID: 7011579f7b96
Revises: 82d8040b722d
Create Date: 2023-12-29 21:05:04.247495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7011579f7b96'
down_revision: Union[str, None] = '82d8040b722d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'file_size')
    # ### end Alembic commands ###
