"""Add deleted_films model

Revision ID: 88f1fc34ca78
Revises: 7011579f7b96
Create Date: 2023-12-29 22:11:50.367720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f1fc34ca78'
down_revision: Union[str, None] = '7011579f7b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_files_id'), 'deleted_files', ['id'], unique=False)
    op.add_column('files', sa.Column('is_favorite', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('files', sa.Column('is_deleted', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_deleted')
    op.drop_column('files', 'is_favorite')
    op.drop_index(op.f('ix_deleted_files_id'), table_name='deleted_files')
    op.drop_table('deleted_files')
    # ### end Alembic commands ###
